name: Lint and Format

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      # Run Black
      - name: Run Black
        run: |
          black --check --diff .
        continue-on-error: true

      # Run isort
      - name: Run isort
        run: |
          isort --check --diff .
        continue-on-error: true

      # Run flake8
      - name: Run flake8
        run: |
          flake8 .
        continue-on-error: true

      # Apply Black and isort if necessary and commit changes
      - name: Apply formatting if needed
        if: failure()
        run: |
          black .
          isort .
        id: format_code
      #    git config --global user.name "GitHub Actions"
      #    git config --global user.email "actions@github.com"
      #    git commit -am "Apply code formatting with Black and isort" || echo "No changes to commit"
      # - name: Push changes
      #   if: failure()
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and Push Branch (if changes)
        if: ${{ steps.format_code.outcome == 'success' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b lint-fix/${{ github.run_id }}
          git add .
          git commit -m "style: auto-format code by linter"
          git push origin lint-fix/${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: lint-fix/${{ github.run_id }}
          base: ${{ github.ref_name}}  # Ursprungsbranch
          title: "style: auto-format code"
          body: |
            This pull request applies automatic formatting to the codebase.